# Generated by Django 5.2 on 2025-04-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_elements_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='elements',
            name='group',
            field=models.CharField(default='', max_length=255),
        ),
    ]
