# Generated by Django 5.2 on 2025-04-06 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_elements_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elements',
            old_name='group',
            new_name='element_group',
        ),
    ]
